In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from pathlib import Path

Path("releases").parent.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(
    "dataset.csv",
    usecols=[
        "Tag",
        "Consumer Claim",
        "Company",
        "Date received",
        "Submitted via",
        "Tags",
        "State"
    ],
    dtype={
        "Tag": "string",
        "Consumer Claim": "string",
        "Company": "string",
        "Submitted via": "string",
        "Tags": "string",
        "State": "string"
    }
)

# affiche les nombres sans notation scientifique avec pandas
pd.set_option("display.float_format", "{:,.2f}".format)

# --------------------------------------------------------------------------
# Normalise les catégories
# --------------------------------------------------------------------------

TAG_MAPPING = {
    # Anciennes catégories → nouvelles catégories
    "Bank account or service":
        "Checking or savings account",

    "Credit reporting":
        "Credit reporting, credit repair services, or other personal consumer reports",

    "Credit card":
        "Credit card or prepaid card",

    "Prepaid card":
        "Credit card or prepaid card",

    "Money transfers":
        "Money transfer, virtual currency, or money service",

    "Virtual currency":
        "Money transfer, virtual currency, or money service",

    "Payday loan":
        "Payday loan, title loan, or personal loan",

    "Consumer Loan":
        "Payday loan, title loan, or personal loan",

    # Catégories déjà dans la nouvelle nomenclature
    "Checking or savings account":
        "Checking or savings account",

    "Debt collection":
        "Debt collection",

    "Credit reporting, credit repair services, or other personal consumer reports":
        "Credit reporting, credit repair services, or other personal consumer reports",

    "Mortgage":
        "Mortgage",

    "Student loan":
        "Student loan",

    "Vehicle loan or lease":
        "Vehicle loan or lease",

    "Credit card or prepaid card":
        "Credit card or prepaid card",

    "Payday loan, title loan, or personal loan":
        "Payday loan, title loan, or personal loan",

    "Money transfer, virtual currency, or money service":
        "Money transfer, virtual currency, or money service",

    "Other financial service":
        "Other financial service",
}

df["Tag"] = df["Tag"].map(TAG_MAPPING)

# --------------------------------------------------------------------------
# Création du dataset
# --------------------------------------------------------------------------

dataset = (
    df
    .loc[df["Tag"] != "Other financial service"]
    .loc[df["Consumer Claim"].notna()]
    .loc[:, [
        "Tag",
        "Consumer Claim"
    ]]
    .drop_duplicates(subset=["Consumer Claim"])
    .copy()
)

# --------------------------------------------------------------------------
# Création du jeu de test/entrainement
# --------------------------------------------------------------------------

X = dataset.drop(columns=["Tag"])
y = dataset["Tag"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,# 20% dans test et 80% dans train
    random_state=42, # seed pour reproduire l'échantillon à l'identique
    stratify=y # Tag possède plusieurs classes, dont certaines beaucoup moins représentées que d'autres
)

In [2]:
dataset.info()

<class 'pandas.DataFrame'>
Index: 366654 entries, 29904 to 912553
Data columns (total 2 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Tag             366654 non-null  str
 1   Consumer Claim  366654 non-null  string
dtypes: str(1), string(1)
memory usage: 409.1 MB

In [3]:
dataset.sample(n=10)

,Tag,Consumer Claim
854256,Mortgage,good faith estimate changed 3 times and intere...
692537,Debt collection,I went to see a doctor @ XXXX XXXX XXXX XXXX X...
480264,Mortgage,I applied for an FHA Home loan with First Comm...
474370,Checking or savings account,I signed up for an HSBC premier checking accou...
558534,Credit card or prepaid card,"Money NEt work, First Data, was given my money..."
602187,Credit card or prepaid card,I have been a customer of capital one for 10 y...
684735,Student loan,I contacted Navient ( my servicer ) and reques...
194316,Mortgage,I HAVE APPLIED FOR FINANCIAL ASSISTANCE DUE TO...
391854,Student loan,We are filing a lawsuit in the amount of XXXX ...
291382,Checking or savings account,Contacted CitibankbCustomer Service on XX/XX/X...

# Vectorisation TF-IDF

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from pathlib import Path
import time

print("Vectorisation...")
start = time.perf_counter()

vectorizer = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    ngram_range=(1, 2), # (1, 2) suffit souvent et évite l'explosion de mémoire subie avec (1, 3)
    min_df=10,
    max_df=0.85,
    max_features=100000,
    sublinear_tf=True,
    stop_words=['xxxx', 'xx', 'xxxx xxxx'] # Nettoyer les masques anonymisés CFPB
)
    
# L'entrainement est réalisé uniquement sur le train
vectorizer.fit(X_train["Consumer Claim"])

elapsed = time.perf_counter() - start
print("Terminé en ", elapsed / 60 if elapsed > 60 else elapsed," (min)" if elapsed > 60 else " (s)")

# transforme les données en vecteur
X_train_tfidf = vectorizer.transform(X_train["Consumer Claim"])

Vectorisation...
Terminé en  1.4804859866664628  (min)

# Entrainement du modèle

In [5]:
from sklearn.svm import LinearSVC

print("Entraine du modèle...")
start = time.perf_counter()

svm = LinearSVC(
    C=1.0,
    class_weight="balanced",
    max_iter=5000
)
svm.fit(X_train_tfidf, y_train)

elapsed = time.perf_counter() - start
print("Terminé en ", elapsed / 60 if elapsed > 60 else elapsed," (min)" if elapsed > 60 else " (s)")

Entraine du modèle...
Terminé en  2.2184091616666897  (min)

# Entrainement du modèle avec calibration

In [6]:
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV, FrozenEstimator

print("Entraine du modèle calibré...")
start = time.perf_counter()

# 1. Envelopper le modèle déjà entraîné (svm) dans un FrozenEstimator
frozen_svm = FrozenEstimator(svm)

# 2. Instancier le calibrateur avec l'estimateur figé
calibrated_svm = CalibratedClassifierCV(frozen_svm)

# 3. Ajuster la calibration le jeu de données (X_train_tfidf, y_train)
calibrated_svm.fit(X_train_tfidf, y_train)

elapsed = time.perf_counter() - start
print("Terminé en ", elapsed / 60 if elapsed > 60 else elapsed," (min)" if elapsed > 60 else " (s)")

Entraine du modèle calibré...
Terminé en  4.761434499989264  (s)

# Test

In [10]:
# Définition du seuil de confiance arbitraire pour un premier test (< 70%)
SEUIL_CONFIANCE = 0.95

In [14]:
from pathlib import Path
from sklearn.pipeline import Pipeline
import time
from metrics import (
    calculate_metrics,
    print_metrics,
    print_report,
)

name = "Test ML v1"
method = "TFIDF + LinearSVC + Calibration"
results_path = Path("tests", name + ".pkl")
 
model = Pipeline([
    ("tfidf", vectorizer),
    ("classifier", calibrated_svm)
])

results = []

for idx in X_test.index:
    question = X_test.loc[idx, "Consumer Claim"]
    expected = y_test.loc[idx]

    start = time.perf_counter()

    y_pred = model.predict([question])[0]
    proba = model.predict_proba([question])[0]
    
    elapsed = time.perf_counter() - start

    results.append({
        "Index": idx,
        "Question": question,
        "Réponse": y_pred,
        "Attendue": expected,
        'Confiance': proba.max(),
        "Correct": y_pred == expected,
        "Temps (s)": elapsed
    })

In [18]:
results = pd.DataFrame(results)

results.head(50)

,Index,Question,Réponse,Attendue,Confiance,Correct,Temps (s)
0,895245,not able to get Equifax report are XXXX repot ...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
1,550620,My property taxes for year XXXX have not been ...,Mortgage,Mortgage,1.00,True,0.01
2,757469,I ordered a spa cover on XXXX the XXXX from XX...,Credit card or prepaid card,Credit card or prepaid card,0.67,True,0.00
3,719214,My email to RushCard sums it up : I have calle...,Credit card or prepaid card,Credit card or prepaid card,0.87,True,0.01
4,904371,Caliber Home Loans took over the servicing of ...,Mortgage,Mortgage,1.00,True,0.00
5,663227,"Listing account as open, charged off by origin...",Debt collection,Debt collection,0.79,True,0.00
6,735782,"im disputing this account, on the basis that i...",Debt collection,Debt collection,0.95,True,0.01
7,483451,Numerous accounts and inquires on my credit re...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
8,837445,We submitted documentation in an attempt to ha...,Mortgage,Mortgage,0.99,True,0.00
9,781784,I accidentally left a check made out to myself...,Checking or savings account,Checking or savings account,1.00,True,0.00
10,250815,My federal student loans through XXXX XXXX wer...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
11,263380,I have a mortgage with Wells Fargo. I refinanc...,Mortgage,Mortgage,0.82,True,0.00
12,353468,"The company called my number today, XXXX XXXX,...",Debt collection,Debt collection,0.99,True,0.00
13,339146,I had a TD checking account that had a {$2500....,Checking or savings account,Checking or savings account,0.93,True,0.00
14,140927,My child support account # XXXX is with XXXX X...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
15,883097,Midland Funding LLC sent false debt collection...,Debt collection,Debt collection,0.99,True,0.00
16,260204,My husband XXXX XXXX XXXX XXXX XXXX after a tw...,Mortgage,Mortgage,0.53,True,0.00
17,311058,Hello my name is XXXX XXXX XXXX and on XX/XX/2...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",0.99,True,0.00
18,401211,"PNC Bank On XX/XX/XXXX, while I was traveling ...",Checking or savings account,Checking or savings account,1.00,True,0.00
19,204328,"I have never had a loan with Navient, and my n...",Student loan,Debt collection,0.99,False,0.00
20,617385,My job was contacted multiple times by people ...,Debt collection,Debt collection,0.93,True,0.00
21,710711,The company Cbe Group keeps harrasing me by ph...,Debt collection,Debt collection,0.99,True,0.00
22,160009,"In XX/XX/2018, I had fallen behind on my loan ...","Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",0.86,True,0.00
23,837678,I wrote and corresponded directly with XXXX an...,Debt collection,"Credit reporting, credit repair services, or o...",0.70,False,0.00
24,310880,"I graduated high school in 2012, and I was in ...",Checking or savings account,Checking or savings account,0.99,True,0.00
25,372544,To Whom it May Concern : I am writing to make ...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
26,898297,Dear OCWEN : This letter serves as the formal ...,Mortgage,Mortgage,0.99,True,0.00
27,342407,OnXX/XX/XXXX I received a copy of my credit re...,Debt collection,Debt collection,0.91,True,0.00
28,829542,We bought a certificate of deposit in the amou...,Checking or savings account,Checking or savings account,0.89,True,0.00
29,534375,I have XXXX charges of XXXX from Gold Key cred...,Debt collection,Debt collection,1.00,True,0.00
30,271801,This debt has been paid. It was supposed to be...,Debt collection,Debt collection,1.00,True,0.00
31,730507,Capital One canceled my current Quicksilver Vi...,Credit card or prepaid card,Credit card or prepaid card,0.99,True,0.00
32,866756,multiple unauthorized inquiries on report,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
33,234031,"On XX/XX/XXXX my husband, XXXX XXXX deposited ...",Checking or savings account,Checking or savings account,0.97,True,0.00
34,734180,I opened a credit card account with XXXX XXXX ...,Credit card or prepaid card,Credit card or prepaid card,0.98,True,0.00
35,668372,Purchased merchandise on XXXX from XXXX in the...,Credit card or prepaid card,Credit card or prepaid card,0.99,True,0.00
36,631434,Approximately a decade ago I filed to permanen...,Credit card or prepaid card,Credit card or prepaid card,0.99,True,0.00
37,769953,I purchased a XXXX XXXX XXXX from XXXX XXXX bu...,"Credit reporting, credit repair services, or o...","Payday loan, title loan, or personal loan",0.65,False,0.00
38,174291,"Upon viewing my credit file with XXXX, XXXX, X...",Debt collection,Debt collection,0.96,True,0.00
39,751131,"Bought house in XXXX XXXX, ( shore mortgage ) ...",Mortgage,Mortgage,0.99,True,0.00
40,750618,XXXX of LoanDepot called me XX/XX/XXXX about r...,Mortgage,Mortgage,0.98,True,0.00
41,399968,"I was contacted on XXXX, XXXX and XXXX by Allt...",Debt collection,Debt collection,1.00,True,0.00
42,658859,Bank of America failed to disclose proper docu...,Mortgage,Mortgage,1.00,True,0.00
43,323793,1. I contacted Experian in XXXX of 2017 about ...,"Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",1.00,True,0.00
44,237700,"XX/XX/XXXX, A FAX AND LETTER WAS SENT TO VALID...","Credit reporting, credit repair services, or o...","Credit reporting, credit repair services, or o...",0.84,True,0.00
45,875582,EOS-CCA is illegally trying to collected a deb...,Debt collection,Debt collection,0.95,True,0.00
46,124104,I received at least 1 XXXX XXXX MasterCard (Ba...,Credit card or prepaid card,Credit card or prepaid card,0.99,True,0.00
47,568498,On XXXX/XXXX/XXXX I look in to my credit repor...,"Credit reporting, credit repair services, or o...",Credit card or prepaid card,1.00,False,0.00
48,196112,First Credit Services located at XXXX XXXX XXX...,Debt collection,Debt collection,0.91,True,0.00
49,654989,In XXXX 2016 we lost out on a short sale buyer...,Mortgage,Mortgage,1.00,True,0.00

In [16]:

metrics = calculate_metrics(name, method, results)

print()
print("------------------------")
print(name)
print("------------------------")
print_metrics(metrics)
print("------------------------")
print_report(results)

------------------------
Test ML v1
------------------------
Name : Test ML v1
Method : TFIDF + LinearSVC + Calibration
Samples : 73331
Accuracy : 84.45%
Precision (macro) : 80.19%
Recall (macro) : 72.99%
F1 (macro) : 75.61%
Precision (weighted) : 84.06%
Recall (weighted) : 84.45%
F1 (weighted) : 84.06%
Temps moyen (s) : 0.0035 s
Temps médian (s) : 0.0033 s
Temps P95 (s) : 0.0047 s

------------------------
                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.82      0.82      0.82      5542
                                                 Credit card or prepaid card       0.81      0.81      0.81      8292
Credit reporting, credit repair services, or other personal consumer reports       0.86      0.89      0.87     22047
                                                             Debt collection       0.82      0.87      0.84     16855
                          Money transfer, virtual currency, or money service       0.88      0.64      0.74      1393
                                                                    Mortgage       0.93      0.94      0.93     10588
                                   Payday loan, title loan, or personal loan       0.63      0.50      0.56      3115
                                                                Student loan       0.92      0.85      0.88      4356
                                                       Vehicle loan or lease       0.55      0.24      0.34      1143

                                                                    accuracy                           0.84     73331
                                                                   macro avg       0.80      0.73      0.76     73331
                                                                weighted avg       0.84      0.84      0.84     73331

# Sauvegarde

In [19]:
import pickle
from metrics import (
    _metrics,
    _report,
)

# sauvegarde les résultats du test
with open("releases/ML_v1.rslt", "wb") as f:
    pickle.dump(results, f)

# sauvegarde le rapport
with open("releases/ML_v1.txt", "w") as f:
    f.write(f"Seuil confiance: {SEUIL_CONFIANCE}" + "\n" + _metrics(metrics) + "\n" + _report(results))

# sauvegarde le modèle
with open("releases/ML_v1.pkl", "wb") as f:
    pickle.dump(model, f)